1.0 to 1.2 Upgrade Logic
Cray-HPE/cray-site-init pull request #108
Opened 2021-12-15 04:38 UTC by SeanWallace

#### Summary and Scope

Contains all the logic necessary to make BSS have all the 1.2 things from a 1.0 start.

MTL-1429

##### Issue Type

Adds all the things for the BSS to be the most happy of services.

#### Prerequisites

- [X ] I have included documentation in my PR (or it is not required)
- [X ] I tested this on internal system (x) (if yes, please include results or a description of the test)
 
#### Idempotency
 
You can run this as much as you want, it computes the correct values from the beginning and then pushes those in.
 
#### Risks and Mitigations
 
Shouldn't be any real risk, this is all new.

2021-12-15 12:11 UTC, jacobsalmela approved these changes

2021-12-15 19:27 UTC, heemstra requested changes
Needs a rebase and some minor linting fixes, but it otherwise looks good to me.  Do we have a ticket for removing existing logic for routes/cloud-init updates from the docs-csm upgrade scripts?

2021-12-15 20:47 UTC, johren-hpe approved these changes

2021-12-15 21:12 UTC, SeanWallace commented
> Needs a rebase and some minor linting fixes, but it otherwise looks good to me. Do we have a ticket for removing existing logic for routes/cloud-init updates from the docs-csm upgrade scripts?

No...and that's a good point, that will need to happen.

2021-12-15 21:17 UTC, heemstra approved these changes

2021-12-15 21:21 UTC, merged

2021-12-16 16:38 UTC, jacobsalmela commented
> Needs a rebase and some minor linting fixes, but it otherwise looks good to me.  Do we have a ticket for removing existing logic for routes/cloud-init updates from the docs-csm upgrade scripts?

There is a companion MTL-1429 docs branch that you can build off of.