MTL-1949: conversion to IMS_IMAGE_ID instead of k8s/ceph version
Cray-HPE/cray-site-init pull request #273
Opened 2022-11-30 15:22 UTC by heemstra

### Summary and Scope

- Fixes: MTL-1949

#### Issue Type

- RFE Pull Request

### Prerequisites

- [ ] I have included documentation in my PR (or it is not required)
- [ ] I tested this on internal system (if yes, please include results or a description of the test)
- [ ] I tested this on a vshasta system (if yes, please include results or a description of the test)
 
### Idempotency
 

 
### Risks and Mitigations

2022-11-30 16:22 UTC, rustydb requested changes

2022-11-30 16:22 UTC, rustydb commented on cmd/handoff-bss-metadata.go
> +			cmdlineParts[i] = fmt.Sprintf("metal.server=%s/%s/rootfs", s3Prefix, imsImageID)
Why not use `rootfsName` incase it ever ever ever changes again?

2022-12-01 19:57 UTC, rustydb approved these changes

2022-12-01 19:57 UTC, rustydb commented on cmd/handoff-bss-metadata.go
> +		versionRegex, err := regexp.Compile(`^[0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12}$`)
Nice.

2022-12-01 21:20 UTC, jacobsalmela commented on cmd/handoff-bss-metadata.go
> +		versionRegex, err := regexp.Compile(`^[0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12}$`)
Kudos

2022-12-01 21:34 UTC, jacobsalmela approved these changes
👋

2022-12-01 21:35 UTC, heemstra commented on cmd/handoff-bss-metadata.go
> +		versionRegex, err := regexp.Compile(`^[0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12}$`)
Internet FTW

2022-12-02 18:16 UTC, mharding-hpe approved these changes

2022-12-02 18:16 UTC, mharding-hpe commented on cmd/handoff-bss-metadata.go
> +			log.Fatalf("ERROR: Could not determine kubernetes image id from [%s]", kubernetesUUID)
```suggestion
			log.Fatalf("ERROR: Could not determine Kubernetes image ID from [%s]", kubernetesUUID)
```

2022-12-02 18:16 UTC, mharding-hpe commented on cmd/handoff-bss-metadata.go
> +			log.Fatalf("ERROR: Could not determine storage image id from [%s]", storageUUID)
```suggestion
			log.Fatalf("ERROR: Could not determine storage image ID from [%s]", storageUUID)
```

2022-12-02 18:16 UTC, mharding-hpe commented on cmd/handoff-bss-metadata.go
> +		"", "The kubernetes IMS_IMAGE_ID UUID value")
```suggestion
		"", "The Kubernetes IMS_IMAGE_ID UUID value")
```

2022-12-02 20:07 UTC, merged